# .rain.yml
project_name: 'app'

version: '0.1.0'

dockers:
  - dockerfile: 'Dockerfile'
    image_templates:
      - 'rain:latest'
      - 'rain:v{{ .Version }}'
    files:
      - glob: scripts/entrypoint.sh
      - glob: rain