# .rain.yml
project_name: 'rain'

version: '0.1.0'

builds:
  - name: 'go'
    command: 'go build -o rain main.go'

dockers:
  - dockerfile: 'Dockerfile'
    image_templates:
      - 'rainproj/rain:latest'
      - 'rainproj/rain:v{{ .Version }}'
    files:
      - glob: scripts/entrypoint.sh
      - glob: rain

pushes:
  - provider: hub